### ISSUE TITLE
Una updater does not say that it is Una

### ISSUE THREAD

**Issue by hiddeninthesand** [AFK-OS/una#11]
As title suggests, the zenity prompt in no way states that it's from Una, leading to a confusing user experience.

**Comment by thisconnected** [comment]
arguably could also be notification rather than full pop up, on X.org it takes focus away from fullscreen windows which is rather jarring

**Comment by hiddeninthesand** [comment]
Is there any way to make it a popunder?

**Comment by RudraSwat** [comment]
Fixed the issue (check #21).
