### ISSUE TITLE
Possibility to turn off una update notifications completely

### ISSUE THREAD

**Issue by jclsn** [AFK-OS/una#14]
I don't need or want a notification asking me to update. It is a really bad solution. While I am typing something, this thing is annoying me and conflicting with my work. 

I understand that you want something for inexperienced users. That is fine, but then it should be done right and triggered as native notifications in the respective desktop environment, e.g. KDE and Gnome. Those can be turned off by the users.

**Comment by jsef5** [comment]
I agree, it is getting pretty annoying

**Comment by sher1** [comment]
I don't think this should be updating the apt repos. There is already a very robust system for doing that as well as sending notifications. My suggestion is that this should focus on mpr

**Comment by capitalistspz** [comment]
Yeah it''s really annoying. I edited `/usr/bin/una-updater` and removed the while loop to stop the hourly pop ups.

**Comment by NinjaCheetah** [comment]
Yeah please do this. It's especially bad when I'm playing a game and my game gets paused just for this popup. Plus I already have an indicator in my tray showing when I have updates, and I think a lot of other DEs do out of the box as well. For now I'm going to do what capitalistspz suggested and edit it.

**Comment by dginovker** [comment]
Big +1 for this - Found this repo so I could make this issue myself.

**Comment by RudraSwat** [comment]
Fixed the issue (check #21).
