### ISSUE TITLE
Cannot disable auto-updater

### ISSUE THREAD

**Issue by ExoPlant** [AFK-OS/una#17]
The auto-updater is really annoying, and happens around every 5 minutes. I would like a way to lengthen the time it takes to once per day to auto update instead of interrupting me every 5 minutes, or just disable the whole thing  and I'll update myself

**Comment by ExoPlant** [comment]
Can someone provide a method of disabling this?

**Comment by FlyinPancake** [comment]
It's so bad

**Comment by Merith-TK** [comment]
like seriously, I left to go shopping and came back to there being sixty popups for una saying there are updates, its worse than windows wants to update,

**Comment by rgvxsthi** [comment]
Hi there,

I managed to get the auto-updater to stop messing with my brain and removing una and the auto-updater by using the following commands (run line-by-line):

 `sudo apt-get remove una-bin`
`sudo apt-get autoremove`
`sudo rm -f /var/lib/una`
`sudo rm /bin/una`
`sudo rm /bin/una-updater`
`sudo rm /bin/una-completion`

**Comment by ExoPlant** [comment]
I don't want to remove una. I want to remove the updater

**Comment by rgvxsthi** [comment]
I believe if you remove the updater i.e. the second last line, it should do the job. Try making a backup of the file and then removing the original una-updater file from /bin/ and see if the annoying pop ups stop.

**Comment by RudraSwat** [comment]
Was planning to reduce the frequency of the auto-updater (yep, it really annoys me too). Been a bit busy with other stuff and will take a look at this.

**Comment by RudraSwat** [comment]
Fixed the issue (check #21).
