### ISSUE TITLE
auto update question boxes stack 

### ISSUE THREAD

**Issue by Admia1** [AFK-OS/una#21]
It happen to me to be away for several hours while my computer is turned on and when I return to work whit my computer i see several Question boxes of una asking to update.

It would be better if it close old boxes before creating new one.

OS : Ubuntu 22.04 LTS
Gnome version: 42.1

Thanks for your great code

**Comment by RudraSwat** [comment]
With the latest update, you can edit /etc/una/config and change the value of `auto_update` to `false` and the default frequency has been decreased (1 day now).
