### ISSUE TITLE
Simplify installation instructions

### ISSUE THREAD

**Issue by hwittenborn** [AFK-OS/una#3]
Hi! I was just looking at your build instructions and noticed the following commands at the bottom:

```sh
una update; sudo mkdir -p /var/lib/una
una help
```

Would there be any reason the `sudo mkdir -p /var/lib/una` command couldn't be put in as a postinst script?

**Comment by hiddeninthesand** [comment]
Would simply installing from the MPR itself not be possible?

**Comment by RudraSwat** [comment]
Hi @hwittenborn! Sure, I've simplified the installation installations (the `/var/lib/una` bit  wasn't required since `una` creates the dir on the first run itself). Closing this issue.
