### ISSUE TITLE
[Feature Request] Helper interoperability

### ISSUE THREAD

**Issue by hiddeninthesand** [AFK-OS/una#4]
As mentioned over Matrix, Tap adds the field `MPR-Package: ${pkgbase}` to the deb's control file. This should let Una recognize that there's previously installed MPR packages, in turn Una should also mark installed packages as MPR packages.

- [x] Mark the packages so other helpers can recognize them
- [x] Read marked packages from APT so Una can recognize packages installed by other helpers

**Comment by RudraSwat** [comment]
I've added the `MPR-Package` field, as well as an `MPR-Version` field with the version of the package in the MPR cache (not pkgver) at the time of installation.
